### ISSUE TITLE
Question about when to add Noise in Stable Diffusion for Score Dist. Sampling?

### ISSUE THREAD

**Issue by JulianKnodt** [ashawkey/stable-dreamfusion#286]
I noticed that in this repo you are adding noise to the image after it has been already passed through the VAE, which seems to differ from the original paper.

After reading fantasia3D, since they use a mask I was trying to apply the mask to the noise itself (altho I'm not quite sure if that's what they do), but since the noise is applied after passing through a VAE it doesn't seem possible. Is there another way to do masking on the noise in the current work?

https://github.com/ashawkey/stable-dreamfusion/blob/42b9193c73842a5904183def95cb7df49ca05642/guidance/sd_utils.py#L105-L120

**Comment by MathieuTuli** [comment]
In the paper, the noise is still added prior to passing through the unet for noise prediction. The same happens here, `self.encode_imgs` isn't the unet, just producing a latent representation of the image for use with the unet. It's to this latent representation that noise is added, not to the original image. Thus this is just a latent diffusion model, operating in latent space rather than operating in the pixel space.

Now I haven't reason Fantasia3D in full yet, from a glance it seems they use a shape encoding of the mask + normal map as inputs to their diffusion model in that first stage. So it's not a simple process of applying the mask to the image or to the noise, but rather leveraging that information to produce a useful latent representation for downstream use, similar in spirit to how we use a latent representation of the image rather than the image itself. I think if you want to experiment with those ideas from Fantasia3D, you should be looking at how you can shape encode the mask information or shape encode the mask + image information to then be passed to the diffusion model.

**Comment by JulianKnodt** [comment]
mmm this makes sense, I guess because of the difference in network this is required.
I assume that working in pixel space for the noise could be made to work as well, but hasn't been done because then it would require more operations to move back to pixel space after diffusion.

I'm not entirely sure what Fantasia3D does, and hopefully once they release their code it should be more transparent what they mean.

**Comment by JulianKnodt** [comment]
Actually, I am still unsure why it matters if this is performed in latent space or image space?

For my specific case, I find that encoding in latent space introduces a lot of localized noise in the output, and am suspecting it may be due to using latent space. I am experimenting with changing it to image space, but is there some justification why it does in latent space other than efficiency?
