### ISSUE TITLE
Multi-card/multi-gpu training.

### ISSUE THREAD

**Issue by Ailon-Island** [ashawkey/stable-dreamfusion#98]
Amazing work! 
I wonder how could I run the model in `DistributedDataParallel` mode as is (seemingly) supported by `nerf\utils\Trainer`. I encountered an OOM while training on GTX 2080Ti with a memory of 11GB. Everything would be nice for me if I were able to train the model on multiple cards.

**Comment by MathieuTuli** [comment]
Have you tried running the code first with a batch size of `1`? I would start there, as this should confirm whether you'll be able to use your GPU setup at all. Meaning, the `DistributedDataParallel` is for distributed training where the data (batches) get parallelized across GPUs, so if for a batch size of `1` you're still getting OOM issues, it's because your GPU doesn't have enough memory for the model, which I believe is the case. I don't believe this code base supports distributed model training, so if you can't run on a single batch size, you'll need bigger GPUs for training.

**Comment by Ailon-Island** [comment]
Ok I was expecting the NeRF component to eat the most memory while actually it is the diffusion model. So paralleling rays for NeRF does not help much. 
Running `guidance` on another GPU instead just makes it runnable without compromising any quality for me on 2080Ti platform.

**Comment by gt732** [comment]
@Ailon-Island can you provide any tips on how you were able to acheive this? I'm using a library very similar to this one that uses a NERF model and SD for guidance. I have 2x 3090s and want to move the guidance to its own GPU but running into issues.

**Comment by Ailon-Island** [comment]
Glad to know my tricks may help! However, it has really been a while since then. I can’t remember most of the details. The main point is that the diffusion model is used in a feed-forward manner without gradient. So you could predict noise with SD on a second card, and calculate/craft the SDS loss on the main card.
